<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="1" time="7.069"><testcase classname="scripts.FileUpload.CheckFileUpload" name="test_local_upload" time="3.57756996155"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/scripts/FileUpload.py&quot;, line 17, in test_local_upload
    preview = self.u.upload(&apos;english_muffin.jpg&apos;)
  File &quot;/Users/adam/work/saunter/py.saunter-examples/picpaste/webdriver/modules/pages/upload.py&quot;, line 54, in upload
    self.accept_rules = true
NameError: global name &apos;true&apos; is not defined</failure></testcase></testsuite>