<?xml version="1.0" encoding="utf-8"?><testsuite name="" errors="0" failures="1" skips="0" tests="6" time="141.042" >
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login" time="0"></testcase>
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login_fails" time="0"><failure message="test failure">E   AssertionError: &apos;Incorrect username or password.&apos; != &apos;This message is deliberately incorrect to trigger a failed test.&apos;</failure></testcase>
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login_from_csv" time="0"></testcase>
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login_from_sqlite3" time="0"></testcase>
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login_with_random_username_and_password" time="0"></testcase>
<testcase classname="scripts.LoginExample.CheckLoginExample" name="test_incorrect_login_with_soft_assert" time="0"></testcase></testsuite>